use_frameworks!

platform :ios, '13.0'

target 'MyFirstPodLib_Example' do
  pod 'MyFirstPodLib', :git => 'https://github.com/leoho0722/MyFirstPodLib.git'

  target 'MyFirstPodLib_Tests' do
    inherit! :search_paths

    
  end
end
